/**
 * Thèmes de mots pour le jeu de l'imposteur.
 * Chaque thème = liste de paires [motCivils, motImposteur].
 *
 * Règle d'or pour les paires : les deux mots doivent être PROCHES
 * (sinon trop facile à démasquer en 1 indice).
 */

export const THEMES = {
  random: {
    label: '🎲 Aléatoire (mélange tous les thèmes)',
    pairs: [],
  },

  superheros: {
    label: '🦸 Super-héros',
    pairs: [
      ['Batman', 'Superman'], ['Spider-Man', 'Daredevil'], ['Iron Man', 'Captain America'],
      ['Hulk', 'Thor'], ['Wolverine', 'Deadpool'], ['Wonder Woman', 'Catwoman'],
      ['Flash', 'Quicksilver'], ['Aquaman', 'Namor'], ['Green Lantern', 'Doctor Strange'],
      ['Black Panther', 'Vision'], ['Joker', 'Lex Luthor'], ['Thanos', 'Darkseid'],
      ['Loki', 'Mystique'], ['Magneto', 'Doctor Doom'], ['Hawkeye', 'Green Arrow'],
      ['Black Widow', 'Catwoman'], ['Storm', 'Jean Grey'], ['Cyclops', 'Nightcrawler'],
      ['Robin', 'Bucky'], ['Captain Marvel', 'Supergirl'], ['Hulk', 'Thing'],
      ['Daredevil', 'Punisher'], ['Iron Man', 'War Machine'], ['Cyclops', 'Havok'],
      ['Wolverine', 'Sabretooth'], ['Doctor Strange', 'Scarlet Witch'], ['Vision', 'Ultron'],
      ['Drax', 'Gamora'], ['Star-Lord', 'Rocket'], ['Groot', 'Mantis'],
      ['Black Widow', 'Hawkeye'], ['Captain America', 'Falcon'], ['Bucky', 'Falcon'],
      ['Spider-Man', 'Venom'], ['Spider-Man', 'Carnage'], ['Goblin', 'Doc Ock'],
      ['Mysterio', 'Vautour'], ['Kingpin', 'Bullseye'], ['Hulk', 'Abomination'],
      ['Iron Man', 'Iron Patriot'], ['Hulk', 'She-Hulk'], ['Spider-Man', 'Spider-Woman'],
      ['Cyclops', 'Storm'], ['Rogue', 'Mystique'], ['Beast', 'Hank McCoy'],
      ['Professor X', 'Magneto'], ['Doctor Strange', 'Wong'], ['Ant-Man', 'Wasp'],
      ['Black Bolt', 'Medusa'], ['Silver Surfer', 'Galactus'], ['Nick Fury', 'Maria Hill'],
      ['Batman', 'Robin'], ['Batgirl', 'Batwoman'], ['Nightwing', 'Red Hood'],
      ['Joker', 'Harley Quinn'], ['Penguin', 'Riddler'], ['Catwoman', 'Poison Ivy'],
      ['Bane', 'Killer Croc'], ['Mr. Freeze', 'Clayface'], ['Two-Face', 'Scarecrow'],
      ['Wonder Woman', 'Hippolyta'], ['Aquaman', 'Mera'], ['Cyborg', 'Vic Stone'],
      ['Green Arrow', 'Black Canary'], ['Flash', 'Reverse-Flash'], ['Zoom', 'Reverse-Flash'],
      ['Black Manta', 'Ocean Master'], ['Darkseid', 'Steppenwolf'], ['Mongul', 'Darkseid'],
      ['Brainiac', 'Lex Luthor'], ['Doomsday', 'Darkseid'], ['Atom', 'Ant-Man'],
      ['Hawkgirl', 'Hawkman'], ['Constantine', 'Zatanna'], ['Swamp Thing', 'Man-Thing'],
      ['Deadshot', 'Deathstroke'], ['Ras al Ghul', 'Talia al Ghul'], ['Hawkeye', 'Mockingbird'],
    ],
  },

  pays: {
    label: '🌍 Pays',
    pairs: [
      ['France', 'Belgique'], ['Japon', 'Chine'], ['Brésil', 'Argentine'],
      ['Espagne', 'Portugal'], ['USA', 'Canada'], ['Allemagne', 'Autriche'],
      ['Norvège', 'Suède'], ['Maroc', 'Algérie'], ['Inde', 'Pakistan'],
      ['Russie', 'Ukraine'], ['Mexique', 'Cuba'], ['Italie', 'Grèce'],
      ['Vietnam', 'Thaïlande'], ['Égypte', 'Tunisie'], ['Corée du Sud', 'Corée du Nord'],
      ['Australie', 'Nouvelle-Zélande'], ['Suisse', 'Liechtenstein'], ['Pays-Bas', 'Danemark'],
      ['Turquie', 'Iran'], ['Pérou', 'Colombie'], ['Sénégal', 'Côte d\'Ivoire'],
      ['Kenya', 'Tanzanie'], ['Afrique du Sud', 'Botswana'], ['Nigeria', 'Ghana'],
      ['Madagascar', 'Maurice'], ['Cambodge', 'Laos'], ['Birmanie', 'Bangladesh'],
      ['Indonésie', 'Philippines'], ['Malaisie', 'Singapour'], ['Mongolie', 'Kazakhstan'],
      ['Ouzbékistan', 'Turkménistan'], ['Géorgie', 'Arménie'], ['Azerbaïdjan', 'Iran'],
      ['Israël', 'Liban'], ['Syrie', 'Jordanie'], ['Iraq', 'Yémen'],
      ['Arabie Saoudite', 'Émirats Arabes Unis'], ['Qatar', 'Bahreïn'], ['Oman', 'Yémen'],
      ['Soudan', 'Éthiopie'], ['Somalie', 'Kenya'], ['Tchad', 'Niger'],
      ['Mali', 'Burkina Faso'], ['Mauritanie', 'Sénégal'], ['Libye', 'Tunisie'],
      ['Cuba', 'Jamaïque'], ['Haïti', 'République Dominicaine'], ['Vénézuela', 'Colombie'],
      ['Chili', 'Bolivie'], ['Paraguay', 'Uruguay'], ['Équateur', 'Pérou'],
      ['Guatemala', 'Honduras'], ['Nicaragua', 'Costa Rica'], ['Panama', 'Costa Rica'],
      ['Islande', 'Groenland'], ['Finlande', 'Estonie'], ['Lettonie', 'Lituanie'],
      ['Pologne', 'Tchéquie'], ['Slovaquie', 'Hongrie'], ['Roumanie', 'Bulgarie'],
      ['Albanie', 'Macédoine'], ['Serbie', 'Croatie'], ['Bosnie', 'Slovénie'],
      ['Monaco', 'Andorre'], ['Vatican', 'Saint-Marin'], ['Malte', 'Chypre'],
      ['Sri Lanka', 'Maldives'], ['Bhoutan', 'Népal'], ['Nouvelle-Calédonie', 'Polynésie'],
      ['Fidji', 'Samoa'], ['Papouasie-Nouvelle-Guinée', 'Indonésie'],
    ],
  },

  nourriture: {
    label: '🍕 Nourriture',
    pairs: [
      ['Pizza', 'Tarte'], ['Hamburger', 'Sandwich'], ['Sushi', 'Maki'],
      ['Salade', 'Soupe'], ['Pâtes', 'Riz'], ['Crêpe', 'Gaufre'],
      ['Fromage', 'Beurre'], ['Pain', 'Brioche'], ['Tomate', 'Poivron'],
      ['Pomme', 'Poire'], ['Bière', 'Vin'], ['Café', 'Thé'],
      ['Chocolat', 'Caramel'], ['Glace', 'Sorbet'], ['Croissant', 'Pain au chocolat'],
      ['Lasagne', 'Cannelloni'], ['Couscous', 'Tajine'], ['Steak', 'Filet mignon'],
      ['Carotte', 'Navet'], ['Yaourt', 'Fromage blanc'], ['Curry', 'Tikka masala'],
      ['Frites', 'Chips'], ['Quiche', 'Tarte salée'], ['Soupe à l\'oignon', 'Velouté'],
      ['Cassoulet', 'Choucroute'], ['Raclette', 'Tartiflette'], ['Fondue', 'Raclette'],
      ['Pot-au-feu', 'Bœuf bourguignon'], ['Ratatouille', 'Caponata'], ['Quiche', 'Pissaladière'],
      ['Tomate', 'Poivron'], ['Concombre', 'Courgette'], ['Aubergine', 'Courgette'],
      ['Salade', 'Crudités'], ['Vinaigrette', 'Sauce'], ['Mayonnaise', 'Aïoli'],
      ['Ketchup', 'Moutarde'], ['Tabasco', 'Sriracha'], ['Soja', 'Worcestershire'],
      ['Pesto', 'Tapenade'], ['Houmous', 'Tzatziki'], ['Guacamole', 'Salsa'],
      ['Sushi', 'Sashimi'], ['Dim sum', 'Bao'], ['Ramen', 'Soba'],
      ['Pad thaï', 'Phở'], ['Tempura', 'Beignet'], ['Wonton', 'Raviolis'],
      ['Tortilla', 'Burrito'], ['Taco', 'Quesadilla'], ['Enchilada', 'Tamale'],
      ['Croissant', 'Chausson'], ['Brioche', 'Pain de mie'], ['Macaron', 'Macaroon'],
      ['Eclair', 'Chouquette'], ['Mille-feuille', 'Religieuse'], ['Tarte tatin', 'Crumble'],
      ['Crème brûlée', 'Crème caramel'], ['Île flottante', 'Œufs à la neige'],
      ['Mousse au chocolat', 'Tiramisu'], ['Cheesecake', 'Tiramisu'], ['Pomme', 'Coing'],
      ['Cerise', 'Griotte'], ['Fraise', 'Framboise'], ['Banane', 'Plantain'],
      ['Mangue', 'Papaye'], ['Litchi', 'Longane'], ['Pastèque', 'Melon'],
      ['Citron', 'Citron vert'], ['Orange', 'Mandarine'], ['Pamplemousse', 'Pomelo'],
      ['Avocat', 'Pistache'], ['Noix', 'Noisette'], ['Amande', 'Cacahuète'],
    ],
  },

  fastfood: {
    label: '🍟 Fast-food',
    pairs: [
      ["McDonald's", 'Burger King'], ['KFC', "Popeye's"], ['Subway', 'Quick'],
      ["Domino's", 'Pizza Hut'], ['Starbucks', 'Costa Coffee'], ['Chipotle', 'Taco Bell'],
      ['Five Guys', 'Shake Shack'], ["O'Tacos", 'Berliner'], ['Sushi Shop', 'Planet Sushi'],
      ['Brioche Dorée', 'Paul'], ['Big Mac', 'Whopper'], ['Nuggets', 'Tenders'],
      ['Wrap', 'Burrito'], ['Milkshake', 'Smoothie'], ['Coca', 'Pepsi'],
      ['Frites McDo', 'Frites BK'], ['Happy Meal', 'King Junior'], ['McFlurry', 'Sundae'],
      ['Tacos français', 'Kebab'], ['Hot-dog', 'Bratwurst'], ['Cheeseburger', 'Double Cheeseburger'],
      ['Salade', 'Wrap salade'], ['McNuggets', 'Chicken Wings'], ['Filet-O-Fish', 'Fish Burger'],
      ['McChicken', 'Crispy Chicken'], ['McMuffin', 'McGriddle'], ['Iced coffee', 'Frappuccino'],
      ['Cookie', 'Brownie'], ['Donut', 'Beignet'], ['Pretzel', 'Gressin'],
      ['Pizza margherita', 'Pizza reine'], ['Pizza 4 fromages', 'Pizza calzone'], ['Pizza pepperoni', 'Pizza chorizo'],
      ['Coca Zero', 'Coca Light'], ['Sprite', '7up'], ['Fanta', 'Mirinda'],
      ['Snickers', 'Mars'], ['Twix', 'Bounty'], ['Kit Kat', 'Lion'],
      ['Oreo', 'Prince'], ['BN', 'Pims'], ['Pim\'s', 'Granola'],
    ],
  },

  animaux: {
    label: '🐾 Animaux',
    pairs: [
      ['Chien', 'Loup'], ['Chat', 'Lion'], ['Cheval', 'Âne'],
      ['Vache', 'Bison'], ['Tigre', 'Léopard'], ['Aigle', 'Faucon'],
      ['Requin', 'Dauphin'], ['Crocodile', 'Alligator'], ['Souris', 'Rat'],
      ['Pigeon', 'Mouette'], ['Poule', 'Canard'], ['Chameau', 'Dromadaire'],
      ['Lapin', 'Lièvre'], ['Éléphant', 'Mammouth'], ['Mouton', 'Chèvre'],
      ['Serpent', 'Lézard'], ['Ours', 'Panda'], ['Singe', 'Gorille'],
      ['Tortue', 'Iguane'], ['Pingouin', 'Manchot'], ['Abeille', 'Guêpe'],
      ['Papillon', 'Libellule'], ['Renard', 'Coyote'], ['Hyène', 'Chacal'],
      ['Buffle', 'Bison'], ['Antilope', 'Gazelle'], ['Zèbre', 'Cheval'],
      ['Hippopotame', 'Rhinocéros'], ['Girafe', 'Okapi'], ['Koala', 'Kangourou'],
      ['Wallaby', 'Kangourou'], ['Quokka', 'Wombat'], ['Tasmanien', 'Wombat'],
      ['Ouistiti', 'Tamarin'], ['Babouin', 'Mandrill'], ['Chimpanzé', 'Bonobo'],
      ['Orang-outan', 'Gorille'], ['Lémurien', 'Maki'], ['Loutre', 'Castor'],
      ['Phoque', 'Otarie'], ['Morse', 'Phoque'], ['Lamantin', 'Dugong'],
      ['Béluga', 'Narval'], ['Orque', 'Cachalot'], ['Espadon', 'Marlin'],
      ['Thon', 'Bonite'], ['Sardine', 'Anchois'], ['Saumon', 'Truite'],
      ['Brochet', 'Sandre'], ['Carpe', 'Tanche'], ['Anguille', 'Murène'],
      ['Pieuvre', 'Calmar'], ['Seiche', 'Calmar'], ['Méduse', 'Anémone'],
      ['Étoile de mer', 'Oursin'], ['Crabe', 'Homard'], ['Langouste', 'Langoustine'],
      ['Crevette', 'Gambas'], ['Moule', 'Huître'], ['Coquille Saint-Jacques', 'Pétoncle'],
      ['Escargot', 'Bulot'], ['Hibou', 'Chouette'], ['Pic-vert', 'Pic épeiche'],
      ['Mésange', 'Pinson'], ['Hirondelle', 'Martinet'], ['Moineau', 'Étourneau'],
      ['Corbeau', 'Corneille'], ['Pie', 'Geai'], ['Toucan', 'Calao'],
      ['Perroquet', 'Perruche'], ['Cacatoès', 'Ara'], ['Flamant rose', 'Spatule'],
      ['Cigogne', 'Héron'], ['Pélican', 'Cormoran'], ['Aigle royal', 'Vautour'],
      ['Cobra', 'Vipère'], ['Boa', 'Python'], ['Mamba noir', 'Cobra'],
      ['Caméléon', 'Iguane'], ['Gecko', 'Caméléon'], ['Crocodile', 'Caïman'],
      ['Tortue marine', 'Tortue terrestre'], ['Salamandre', 'Triton'], ['Grenouille', 'Crapaud'],
    ],
  },

  metiers: {
    label: '👨‍🍳 Métiers',
    pairs: [
      ['Médecin', 'Infirmier'], ['Boulanger', 'Pâtissier'], ['Pompier', 'Policier'],
      ['Avocat', 'Juge'], ['Acteur', 'Chanteur'], ['Pilote', 'Hôtesse de l\'air'],
      ['Cuisinier', 'Serveur'], ['Architecte', 'Ingénieur'], ['Journaliste', 'Écrivain'],
      ['Coiffeur', 'Barbier'], ['Mécanicien', 'Garagiste'], ['Plombier', 'Électricien'],
      ['Professeur', 'Instituteur'], ['Vétérinaire', 'Médecin'], ['Photographe', 'Cinéaste'],
      ['DJ', 'Musicien'], ['Boucher', 'Charcutier'], ['Jardinier', 'Paysagiste'],
      ['Pêcheur', 'Marin'], ['Astronaute', 'Pilote de chasse'], ['Dentiste', 'Orthodontiste'],
      ['Kinésithérapeute', 'Ostéopathe'], ['Psychologue', 'Psychiatre'], ['Notaire', 'Avocat'],
      ['Comptable', 'Gestionnaire'], ['Banquier', 'Trader'], ['Commercial', 'Vendeur'],
      ['Caissier', 'Vendeur'], ['Boulanger', 'Pâtissier'], ['Cuisinier', 'Chef'],
      ['Sommelier', 'Œnologue'], ['Pâtissier', 'Chocolatier'], ['Fleuriste', 'Jardinier'],
      ['Couturier', 'Tailleur'], ['Styliste', 'Couturier'], ['Designer', 'Graphiste'],
      ['Peintre', 'Sculpteur'], ['Musicien', 'Compositeur'], ['Acteur', 'Comédien'],
      ['Chanteur', 'Chanteuse'], ['Danseur', 'Chorégraphe'], ['Réalisateur', 'Producteur'],
      ['Romancier', 'Poète'], ['Journaliste', 'Reporter'], ['Présentateur', 'Animateur'],
      ['Programmeur', 'Développeur'], ['Hacker', 'Pirate'], ['Webdesigner', 'UX designer'],
      ['Ingénieur', 'Technicien'], ['Architecte', 'Urbaniste'], ['Géomètre', 'Topographe'],
      ['Maçon', 'Charpentier'], ['Couvreur', 'Toitureur'], ['Menuisier', 'Ébéniste'],
      ['Carrossier', 'Peintre auto'], ['Marin', 'Pêcheur'], ['Capitaine', 'Marin'],
      ['Pilote', 'Copilote'], ['Steward', 'Hôtesse'], ['Contrôleur aérien', 'Pilote'],
      ['Chauffeur', 'Routier'], ['Taxi', 'VTC'], ['Cheminot', 'Conducteur de train'],
      ['Soldat', 'Officier'], ['Général', 'Colonel'], ['Marine', 'Soldat'],
      ['Diplomate', 'Ambassadeur'], ['Politique', 'Ministre'], ['Maire', 'Conseiller'],
    ],
  },

  sports: {
    label: '⚽ Sports',
    pairs: [
      ['Football', 'Rugby'], ['Tennis', 'Badminton'], ['Basket', 'Handball'],
      ['Ski', 'Snowboard'], ['Natation', 'Plongée'], ['Boxe', 'Karaté'],
      ['Cyclisme', 'Triathlon'], ['Volley', 'Beach-volley'], ['Golf', 'Mini-golf'],
      ['Athlétisme', 'Marathon'], ['Échecs', 'Dames'], ['Surf', 'Kitesurf'],
      ['Escalade', 'Alpinisme'], ['Hockey', 'Crosse'], ['Baseball', 'Cricket'],
      ['Judo', 'Lutte'], ['F1', 'MotoGP'], ['Pétanque', 'Curling'],
      ['Aviron', 'Canoë'], ['Patinage', 'Roller'], ['Karaté', 'Taekwondo'],
      ['Aïkido', 'Jiu-jitsu'], ['Krav Maga', 'MMA'], ['Boxe française', 'Savate'],
      ['Boxe', 'Kickboxing'], ['Muay-thaï', 'Kickboxing'], ['Sumo', 'Lutte'],
      ['Course à pied', 'Marathon'], ['Sprint', 'Course de haies'], ['Saut en hauteur', 'Saut en longueur'],
      ['Lancer de javelot', 'Lancer de poids'], ['Lancer de marteau', 'Lancer de disque'],
      ['Décathlon', 'Heptathlon'], ['Pentathlon', 'Triathlon'], ['Orienteering', 'Trail'],
      ['Ski alpin', 'Ski de fond'], ['Saut à ski', 'Combiné nordique'], ['Slalom', 'Descente'],
      ['Bobsleigh', 'Luge'], ['Biathlon', 'Combiné nordique'], ['Patin de vitesse', 'Patinage artistique'],
      ['Hockey sur glace', 'Hockey sur gazon'], ['Cricket', 'Baseball'], ['Softball', 'Baseball'],
      ['Polo', 'Hockey'], ['Polo aquatique', 'Water-polo'], ['Plongeon', 'Natation synchronisée'],
      ['Plongée sous-marine', 'Apnée'], ['Voile', 'Aviron'], ['Surf', 'Bodyboard'],
      ['Wakeboard', 'Ski nautique'], ['Kayak', 'Canoë'], ['Rafting', 'Hydrospeed'],
      ['Skateboard', 'Roller'], ['BMX', 'VTT'], ['Trial', 'Cross'],
      ['Motocross', 'Enduro'], ['Rallye', 'F1'], ['Karting', 'F1'],
      ['Bowling', 'Quilles'], ['Billard américain', 'Snooker'], ['Snooker', 'Pool'],
      ['Fléchettes', 'Tir à l\'arc'], ['Tir au pistolet', 'Tir à la carabine'],
      ['Escrime', 'Sabre'], ['Fleuret', 'Épée'], ['Judo', 'Aïkido'],
      ['Cheerleading', 'Pom-pom girls'], ['Gymnastique', 'Acrobatie'], ['Trampoline', 'Tumbling'],
    ],
  },

  films: {
    label: '🎬 Films & séries',
    pairs: [
      ['Star Wars', 'Star Trek'], ['Harry Potter', 'Le Seigneur des Anneaux'],
      ['Avengers', 'Justice League'], ['Friends', 'How I Met Your Mother'],
      ['Game of Thrones', 'The Witcher'], ['Breaking Bad', 'Better Call Saul'],
      ['Stranger Things', 'Dark'], ['Peaky Blinders', 'The Sopranos'],
      ['La Casa de Papel', 'Lupin'], ['Lost', 'Westworld'],
      ['Spider-Man', 'Batman'], ['Le Roi Lion', 'Madagascar'],
      ['Titanic', 'Avatar'], ['Jurassic Park', 'King Kong'],
      ['Indiana Jones', 'Tomb Raider'], ['Matrix', 'Inception'],
      ['Pirates des Caraïbes', 'Capitaine Crochet'], ['Le Parrain', 'Scarface'],
      ['Toy Story', 'Monstres et Cie'], ['Shrek', 'Madagascar'],
      ['Le Hobbit', 'Le Seigneur des Anneaux'], ['Marvel', 'DC'],
      ['Iron Man', 'Captain America'], ['Thor', 'Hulk'],
      ['Wonder Woman', 'Aquaman'], ['Black Panther', 'Black Widow'],
      ['The Mandalorian', 'Boba Fett'], ['Squid Game', 'Alice in Borderland'],
      ['Prison Break', 'Money Heist'], ['Vikings', 'The Last Kingdom'],
      ['House of Cards', 'Designated Survivor'], ['Suits', 'How to Get Away with Murder'],
      ['Sex and the City', 'Gossip Girl'], ['Modern Family', 'Brooklyn Nine-Nine'],
      ['The Office', 'Parks and Recreation'], ['Ted Lasso', 'Schitt\'s Creek'],
      ['Black Mirror', 'The Twilight Zone'], ['American Horror Story', 'The Haunting'],
      ['Walking Dead', 'Z Nation'], ['Money Heist', 'Lupin'],
      ['Ozark', 'Bloodline'], ['Narcos', 'El Chapo'],
      ['Mr. Robot', 'Westworld'], ['Mindhunter', 'True Detective'],
      ['Sherlock', 'Elementary'], ['Doctor Who', 'Torchwood'],
      ['Big Bang Theory', 'Young Sheldon'], ['Friends', 'Seinfeld'],
      ['Two and a Half Men', 'Big Bang Theory'], ['Lost', 'The 100'],
      ['Heroes', 'Misfits'], ['The Office UK', 'The Office US'],
      ['Parks & Rec', 'The Office'], ['Arrested Development', 'It\'s Always Sunny'],
      ['Avatar', 'Avatar 2'], ['Mad Max', 'Fury Road'],
      ['Le Hobbit', 'Bilbo'], ['Star Wars', 'The Mandalorian'],
      ['Mission Impossible', 'James Bond'], ['Jason Bourne', 'James Bond'],
      ['Rocky', 'Creed'], ['Karate Kid', 'Cobra Kai'],
      ['Top Gun', 'Top Gun Maverick'], ['Fast & Furious', 'Tokyo Drift'],
    ],
  },

  objets: {
    label: '📱 Objets du quotidien',
    pairs: [
      ['Téléphone', 'Tablette'], ['Stylo', 'Crayon'], ['Vélo', 'Trottinette'],
      ['Voiture', 'Moto'], ['Ordinateur', 'Console'], ['Télévision', 'Projecteur'],
      ['Lit', 'Canapé'], ['Chaise', 'Tabouret'], ['Lampe', 'Bougie'],
      ['Frigo', 'Congélateur'], ['Four', 'Micro-ondes'], ['Aspirateur', 'Balai'],
      ['Sac à dos', 'Valise'], ['Lunettes', 'Loupe'], ['Montre', 'Bracelet'],
      ['Casque', 'Écouteurs'], ['Parapluie', 'Imperméable'], ['Couteau', 'Fourchette'],
      ['Livre', 'Magazine'], ['Clavier', 'Souris'], ['Imprimante', 'Scanner'],
      ['Téléphone fixe', 'Talkie-walkie'], ['Caméra', 'Appareil photo'], ['GPS', 'Boussole'],
      ['Calculatrice', 'Abaque'], ['Cahier', 'Carnet'], ['Agenda', 'Planning'],
      ['Trousse', 'Pochette'], ['Cartable', 'Sac à dos'], ['Sac à main', 'Pochette'],
      ['Portefeuille', 'Porte-monnaie'], ['Carte bleue', 'Chèque'], ['Clé', 'Cadenas'],
      ['Porte-clés', 'Trousseau'], ['Tournevis', 'Marteau'], ['Scie', 'Cutter'],
      ['Mètre', 'Réglet'], ['Niveau', 'Équerre'], ['Perceuse', 'Visseuse'],
      ['Pelle', 'Râteau'], ['Bêche', 'Houe'], ['Sécateur', 'Cisaille'],
      ['Tondeuse', 'Tronçonneuse'], ['Échelle', 'Escabeau'], ['Tabouret', 'Chaise'],
      ['Banc', 'Banquette'], ['Fauteuil', 'Canapé'], ['Hamac', 'Transat'],
      ['Coussin', 'Oreiller'], ['Couette', 'Couverture'], ['Drap', 'Housse'],
      ['Serviette', 'Drap de bain'], ['Gant de toilette', 'Éponge'], ['Brosse à dents', 'Cure-dent'],
      ['Peigne', 'Brosse'], ['Sèche-cheveux', 'Lisseur'], ['Rasoir', 'Tondeuse'],
      ['Miroir', 'Glace'], ['Pince à épiler', 'Coupe-ongle'], ['Pansement', 'Bandage'],
      ['Thermomètre', 'Tensiomètre'], ['Stéthoscope', 'Otoscope'], ['Seringue', 'Aiguille'],
      ['Couteau de cuisine', 'Couteau à pain'], ['Cuillère', 'Louche'], ['Spatule', 'Maryse'],
      ['Casserole', 'Poêle'], ['Cocotte', 'Marmite'], ['Saladier', 'Bol'],
      ['Assiette', 'Coupelle'], ['Verre', 'Tasse'], ['Mug', 'Tasse'],
      ['Carafe', 'Bouteille'], ['Ouvre-boîte', 'Décapsuleur'], ['Tire-bouchon', 'Limonadier'],
    ],
  },

  lieux: {
    label: '🏖️ Lieux',
    pairs: [
      ['Plage', 'Piscine'], ['Forêt', 'Jungle'], ['Montagne', 'Colline'],
      ['Restaurant', 'Cantine'], ['Bibliothèque', 'Librairie'], ['École', 'Université'],
      ['Hôpital', 'Clinique'], ['Hôtel', 'Auberge'], ['Musée', 'Galerie'],
      ['Cinéma', 'Théâtre'], ['Parc', 'Jardin'], ['Désert', 'Toundra'],
      ['Zoo', 'Aquarium'], ['Aéroport', 'Gare'], ['Église', 'Cathédrale'],
      ['Marché', 'Supermarché'], ['Stade', 'Gymnase'], ['Pharmacie', 'Parapharmacie'],
      ['Banque', 'Poste'], ['Boîte de nuit', 'Bar'], ['Mosquée', 'Synagogue'],
      ['Temple', 'Pagode'], ['Chapelle', 'Église'], ['Cimetière', 'Catacombes'],
      ['Crypte', 'Caveau'], ['Château', 'Palais'], ['Donjon', 'Tour'],
      ['Prison', 'Donjon'], ['Tribunal', 'Palais de justice'], ['Mairie', 'Préfecture'],
      ['Ambassade', 'Consulat'], ['Gare TGV', 'Métro'], ['Tramway', 'Bus'],
      ['Téléphérique', 'Funiculaire'], ['Port', 'Marina'], ['Phare', 'Sémaphore'],
      ['Plage', 'Crique'], ['Lagon', 'Atoll'], ['Île', 'Archipel'],
      ['Falaise', 'Précipice'], ['Vallée', 'Gorge'], ['Canyon', 'Ravin'],
      ['Glacier', 'Iceberg'], ['Volcan', 'Cratère'], ['Geyser', 'Source chaude'],
      ['Caverne', 'Grotte'], ['Mine', 'Carrière'], ['Souterrain', 'Tunnel'],
      ['Pont', 'Viaduc'], ['Aqueduc', 'Pont'], ['Barrage', 'Digue'],
      ['Canal', 'Rivière'], ['Fleuve', 'Affluent'], ['Lac', 'Étang'],
      ['Marais', 'Bayou'], ['Mangrove', 'Marais'], ['Savane', 'Steppe'],
      ['Prairie', 'Pampa'], ['Banquise', 'Glacier'], ['Pôle', 'Cercle polaire'],
      ['Place', 'Esplanade'], ['Avenue', 'Boulevard'], ['Rue', 'Ruelle'],
      ['Allée', 'Sentier'], ['Trottoir', 'Chaussée'], ['Rond-point', 'Carrefour'],
      ['Centre commercial', 'Galerie marchande'], ['Boutique', 'Échoppe'],
      ['Salon de beauté', 'Spa'], ['Sauna', 'Hammam'], ['Salle de sport', 'Piscine'],
      ['Court de tennis', 'Stade'], ['Aire de jeux', 'Parc'], ['Terrasse', 'Balcon'],
      ['Véranda', 'Pergola'], ['Garage', 'Hangar'], ['Cabane', 'Cabanon'],
      ['Yourte', 'Tipi'], ['Tente', 'Bivouac'], ['Camping', 'Bungalow'],
    ],
  },

  // ───────── Nouveaux thèmes ─────────

  vehicules: {
    label: '🚗 Véhicules',
    pairs: [
      ['Voiture', 'Moto'], ['Camion', 'Bus'], ['Vélo', 'Trottinette'],
      ['Avion', 'Hélicoptère'], ['Bateau', 'Sous-marin'], ['Train', 'Métro'],
      ['Tramway', 'Bus'], ['Camionnette', 'Fourgon'], ['Quad', 'Jet ski'],
      ['Skateboard', 'Roller'], ['Scooter', 'Mobylette'], ['Karting', 'Buggy'],
      ['Ferrari', 'Lamborghini'], ['Porsche', 'Audi'], ['BMW', 'Mercedes'],
      ['Tesla', 'Renault Zoé'], ['Renault', 'Peugeot'], ['Citroën', 'Renault'],
      ['Toyota', 'Honda'], ['Nissan', 'Mazda'], ['Hyundai', 'Kia'],
      ['Ford', 'Chevrolet'], ['Jeep', 'Land Rover'], ['Range Rover', 'Mercedes G'],
      ['SUV', 'Crossover'], ['Citadine', 'Compacte'], ['Berline', 'Coupé'],
      ['Cabriolet', 'Roadster'], ['Break', 'Monospace'], ['Pick-up', 'Utilitaire'],
      ['Boeing', 'Airbus'], ['Concorde', 'A380'], ['Hélicoptère', 'Drone'],
      ['Montgolfière', 'Dirigeable'], ['Planeur', 'ULM'], ['Parachute', 'Parapente'],
      ['Train à vapeur', 'TGV'], ['RER', 'Métro'], ['Tramway', 'Trolleybus'],
      ['Cargo', 'Pétrolier'], ['Voilier', 'Yacht'], ['Catamaran', 'Trimaran'],
      ['Kayak', 'Canoë'], ['Pédalo', 'Barque'], ['Gondole', 'Pirogue'],
    ],
  },

  marques: {
    label: '🏷️ Marques connues',
    pairs: [
      ['Apple', 'Samsung'], ['Nike', 'Adidas'], ['Coca-Cola', 'Pepsi'],
      ['Google', 'Microsoft'], ['Facebook', 'Twitter'], ['Instagram', 'Snapchat'],
      ['YouTube', 'TikTok'], ['Netflix', 'Disney+'], ['Amazon', 'eBay'],
      ['Tesla', 'BMW'], ['Mercedes', 'Audi'], ['Rolex', 'Tag Heuer'],
      ['Chanel', 'Dior'], ['Louis Vuitton', 'Gucci'], ['Hermès', 'Prada'],
      ['Zara', 'H&M'], ['Uniqlo', 'Gap'], ['Lacoste', 'Polo Ralph Lauren'],
      ['Nutella', 'Speculoos'], ['Coca-Cola', 'Pepsi'], ['Starbucks', 'Costa'],
      ['McDonald\'s', 'Burger King'], ['KFC', 'Popeye\'s'], ['Subway', 'Quick'],
      ['Sony', 'Microsoft Xbox'], ['PlayStation', 'Xbox'], ['Nintendo', 'Sega'],
      ['Spotify', 'Deezer'], ['Apple Music', 'Spotify'], ['Tidal', 'Spotify'],
      ['Uber', 'Lyft'], ['Airbnb', 'Booking'], ['Booking', 'Hotels.com'],
      ['Tripadvisor', 'Yelp'], ['IKEA', 'Conforama'], ['Castorama', 'Leroy Merlin'],
      ['Carrefour', 'Auchan'], ['Lidl', 'Aldi'], ['Monoprix', 'Casino'],
      ['Air France', 'Ryanair'], ['Easyjet', 'Ryanair'], ['Lufthansa', 'British Airways'],
      ['Ferrari', 'Lamborghini'], ['Porsche', 'Aston Martin'], ['Bentley', 'Rolls-Royce'],
      ['Vans', 'Converse'], ['Puma', 'Reebok'], ['Asics', 'New Balance'],
    ],
  },

  jeux_video: {
    label: '🎮 Jeux vidéo & personnages',
    pairs: [
      ['Mario', 'Luigi'], ['Sonic', 'Knuckles'], ['Link', 'Zelda'],
      ['Pikachu', 'Raichu'], ['Pacman', 'Tetris'], ['Master Chief', 'Doomguy'],
      ['Lara Croft', 'Indiana Jones'], ['Solid Snake', 'Big Boss'], ['Cloud', 'Sephiroth'],
      ['Ezio', 'Altair'], ['Geralt', 'Yennefer'], ['Kratos', 'Atreus'],
      ['Mario', 'Wario'], ['Bowser', 'Wario'], ['Yoshi', 'Toad'],
      ['Princesse Peach', 'Princesse Daisy'], ['Donkey Kong', 'Diddy Kong'], ['Kirby', 'King Dedede'],
      ['Sonic', 'Tails'], ['Tails', 'Knuckles'], ['Shadow', 'Sonic'],
      ['Link', 'Ganon'], ['Zelda', 'Hyrule'], ['Samus', 'Master Chief'],
      ['Pikachu', 'Salamèche'], ['Bulbizarre', 'Carapuce'], ['Mewtwo', 'Mew'],
      ['Lugia', 'Ho-Oh'], ['Rayquaza', 'Kyogre'], ['Dialga', 'Palkia'],
      ['Pac-Man', 'Ms. Pac-Man'], ['Tetris', 'Puyo Puyo'], ['Candy Crush', 'Bejeweled'],
      ['Among Us', 'Fall Guys'], ['Fortnite', 'PUBG'], ['Apex Legends', 'Warzone'],
      ['Call of Duty', 'Battlefield'], ['CoD MW', 'CoD Black Ops'], ['Counter-Strike', 'Valorant'],
      ['League of Legends', 'Dota 2'], ['LoL', 'Smite'], ['HotS', 'Heroes of the Storm'],
      ['World of Warcraft', 'Final Fantasy XIV'], ['WoW', 'Guild Wars 2'], ['Runescape', 'Tibia'],
      ['Minecraft', 'Roblox'], ['Terraria', 'Starbound'], ['Stardew Valley', 'Animal Crossing'],
      ['GTA V', 'Red Dead Redemption 2'], ['GTA San Andreas', 'GTA Vice City'], ['Mafia', 'GTA'],
      ['The Witcher 3', 'Skyrim'], ['Skyrim', 'Oblivion'], ['Morrowind', 'Skyrim'],
      ['Elden Ring', 'Dark Souls'], ['Dark Souls', 'Bloodborne'], ['Sekiro', 'Nioh'],
      ['Resident Evil', 'Silent Hill'], ['RE4', 'RE2 Remake'], ['Outlast', 'Amnesia'],
      ['FIFA', 'PES'], ['NBA 2K', 'NBA Live'], ['NHL', 'Madden NFL'],
      ['Mario Kart', 'Crash Team Racing'], ['Gran Turismo', 'Forza'], ['Need for Speed', 'Ridge Racer'],
      ['Tony Hawk', 'Skate'], ['SSX', 'Steep'], ['1080° Snowboarding', 'Cool Boarders'],
      ['Street Fighter', 'Mortal Kombat'], ['Tekken', 'Soul Calibur'], ['Smash Bros', 'PlayStation All-Stars'],
    ],
  },

  boissons: {
    label: '🍷 Boissons',
    pairs: [
      ['Eau', 'Eau pétillante'], ['Coca', 'Pepsi'], ['Sprite', '7up'],
      ['Fanta', 'Orangina'], ['Café', 'Thé'], ['Café espresso', 'Café latte'],
      ['Cappuccino', 'Macchiato'], ['Thé vert', 'Thé noir'], ['Tisane', 'Infusion'],
      ['Chocolat chaud', 'Lait'], ['Smoothie', 'Milkshake'], ['Jus d\'orange', 'Jus de pomme'],
      ['Bière', 'Cidre'], ['Bière blonde', 'Bière brune'], ['Vin rouge', 'Vin blanc'],
      ['Vin rosé', 'Vin blanc'], ['Champagne', 'Crémant'], ['Whisky', 'Bourbon'],
      ['Rhum', 'Tequila'], ['Vodka', 'Gin'], ['Cognac', 'Armagnac'],
      ['Mojito', 'Caïpirinha'], ['Cuba Libre', 'Mojito'], ['Pina Colada', 'Daiquiri'],
      ['Margarita', 'Tequila Sunrise'], ['Bloody Mary', 'Sangria'], ['Cosmopolitan', 'Cosmo'],
      ['Spritz', 'Aperol'], ['Kir', 'Kir Royal'], ['Pastis', 'Anisette'],
      ['Sake', 'Soju'], ['Saké', 'Vin de riz'], ['Shōchū', 'Saké'],
      ['Thé matcha', 'Thé vert'], ['Yerba Mate', 'Thé'], ['Kombucha', 'Kéfir'],
      ['Lait', 'Lait d\'amande'], ['Lait d\'avoine', 'Lait d\'amande'], ['Lait de soja', 'Lait de coco'],
      ['Schweppes', 'Tonic'], ['Limonade', 'Diabolo'], ['Sirop', 'Grenadine'],
      ['Coca Zero', 'Coca Light'], ['Red Bull', 'Monster'], ['Powerade', 'Gatorade'],
    ],
  },

  capitales: {
    label: '🏙️ Capitales',
    pairs: [
      ['Paris', 'Lyon'], ['Londres', 'Manchester'], ['Berlin', 'Munich'],
      ['Madrid', 'Barcelone'], ['Rome', 'Milan'], ['Tokyo', 'Osaka'],
      ['Pékin', 'Shanghai'], ['Moscou', 'Saint-Pétersbourg'], ['Washington', 'New York'],
      ['Ottawa', 'Toronto'], ['Brasília', 'Rio'], ['Buenos Aires', 'Cordoba'],
      ['Mexico', 'Guadalajara'], ['Le Caire', 'Alexandrie'], ['Rabat', 'Casablanca'],
      ['Alger', 'Oran'], ['Tunis', 'Sfax'], ['Dakar', 'Saint-Louis'],
      ['Abidjan', 'Yamoussoukro'], ['Lagos', 'Abuja'], ['Nairobi', 'Mombasa'],
      ['Pretoria', 'Johannesbourg'], ['New Delhi', 'Mumbai'], ['Bangkok', 'Phuket'],
      ['Hanoï', 'Hô Chi Minh-Ville'], ['Manille', 'Cebu'], ['Jakarta', 'Bali'],
      ['Séoul', 'Busan'], ['Pyongyang', 'Séoul'], ['Riyad', 'Djeddah'],
      ['Téhéran', 'Ispahan'], ['Bagdad', 'Bassora'], ['Damas', 'Alep'],
      ['Beyrouth', 'Tripoli'], ['Amman', 'Pétra'], ['Jérusalem', 'Tel-Aviv'],
      ['Ankara', 'Istanbul'], ['Athènes', 'Thessalonique'], ['Lisbonne', 'Porto'],
      ['Bruxelles', 'Anvers'], ['Amsterdam', 'Rotterdam'], ['Berne', 'Zurich'],
      ['Vienne', 'Salzbourg'], ['Prague', 'Brno'], ['Varsovie', 'Cracovie'],
      ['Budapest', 'Debrecen'], ['Stockholm', 'Göteborg'], ['Oslo', 'Bergen'],
      ['Copenhague', 'Aarhus'], ['Helsinki', 'Tampere'], ['Reykjavik', 'Akureyri'],
      ['Dublin', 'Cork'], ['Édimbourg', 'Glasgow'], ['Cardiff', 'Swansea'],
      ['Hong Kong', 'Macao'], ['Singapour', 'Kuala Lumpur'], ['Kuala Lumpur', 'Penang'],
    ],
  },
};

// Remplir 'random' avec toutes les paires des autres thèmes
THEMES.random.pairs = Object.values(THEMES)
  .filter(t => t !== THEMES.random)
  .flatMap(t => t.pairs);

// ───────── API publique ─────────

export function listThemes() {
  return Object.entries(THEMES).map(([id, t]) => ({
    id,
    label: t.label,
    pairCount: t.pairs.length,
  }));
}

export function pickRandomPair(themeId = 'random') {
  const theme = THEMES[themeId] || THEMES.random;
  return theme.pairs[Math.floor(Math.random() * theme.pairs.length)];
}

export function isValidTheme(themeId) {
  return themeId in THEMES;
}
